//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookselling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bill
    {
        public int Bill_ID { get; set; }

        public int Book_ID { get; set; }
        public System.DateTime Bill_Date { get; set; }
        [Required(ErrorMessage = "A Total price is required")]
        public int Total_Price { get; set; }
        [Required(ErrorMessage = "A Quantity is required")]
        public int Quantity { get; set; }
        public int Invoice { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Invoice Invoice1 { get; set; }
    }
}
