//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookselling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Bills = new HashSet<Bill>();
            this.Customers = new HashSet<Customer>();
            this.Seller_Bill = new HashSet<Seller_Bill>();
        }
    
        public int Book_ID { get; set; }
        [Required(ErrorMessage = "A Book name is required")]
        [Remote("IsbookExists", "Book", ErrorMessage = "Book Name already in use")]
        public string Book_Name { get; set; }
        public string Genre { get; set; }
        [Required(ErrorMessage = "A Genre name is required")]
        public int Publisher { get; set; }
        [Required(ErrorMessage = "A cost price is required")]
        public int Cost_Price { get; set; }
        [Required(ErrorMessage = "A sell price is required")]
        public int Sell_price { get; set; }
        [Required(ErrorMessage = "A Quantity name is required")]
        public int Quantity { get; set; }
        public int Employee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Seller Seller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seller_Bill> Seller_Bill { get; set; }
    }
}
