//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookselling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Books = new HashSet<Book>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int Emp_ID { get; set; }
       
        [Required(ErrorMessage = "A Employee name is required")]
        public string Emp_Name { get; set; }
        [Required(ErrorMessage = "A phone  is required")]
     //   [MinLength(11, ErrorMessage = "length should be greater then 10")]
        public long Phone_Number { get; set; }
        [Required(ErrorMessage = "A salary  is required")]
        public int Salary { get; set; }
     //   [Required(ErrorMessage = "A Employee name is required")]
        public int users_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
