//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookselling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Seller_Bill
    {
        public int Id { get; set; }
        public int Book { get; set; }
        public int Publisher { get; set; }
        [Required(ErrorMessage = "A Total amount is required")]
        public int Total_Amount { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Book Book1 { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
